#!/usr/bin/env python3
# Copyright (C) 2026 RZ781
#
# This file is part of bman.
#
# bman is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bman is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.

import os, shutil, subprocess, json, typing, argparse

class GitSourceConfig(typing.TypedDict):
    type: typing.Literal["git"]
    remote: str
    branch: typing.Optional[str]

class CommandBuildConfig(typing.TypedDict):
    type: typing.Literal["command"]
    command: str

class PackageConfig(typing.TypedDict):
    source: GitSourceConfig
    build: CommandBuildConfig

data_dir = os.environ.get("BMAN_DATA_DIR", os.path.expanduser(f"~/.local/share/bman"))
config_dir = os.environ.get("BMAN_CONFIG_DIR", os.path.expanduser(f"~/.config/bman"))

def install_package(pkg_name: str, config: PackageConfig) -> None:
    clone_command = ["git", "clone", config["source"]["remote"], pkg_name, "--depth", "1"]
    if config["source"]["branch"] is not None:
        clone_command += ["--branch", config["source"]["branch"]]
    subprocess.run(clone_command, cwd=data_dir)
    subprocess.run(["git", "submodule", "update", "--init"], cwd=f"{data_dir}/{pkg_name}")
    subprocess.run(config["build"]["command"], cwd=f"{data_dir}/{pkg_name}", shell=True)
    with open(f"{config_dir}/{pkg_name}.json", "w") as f:
        json.dump(config, f)

def remove_package(pkg_name: str) -> None:
    shutil.rmtree(f"{data_dir}/{pkg_name}")
    os.remove(f"{config_dir}/{pkg_name}.json")

def update_package(pkg_name: str) -> None:
    with open(f"{config_dir}/{pkg_name}.json") as f:
        config: PackageConfig = json.load(f)
    subprocess.run(["git", "pull"], cwd=f"{data_dir}/{pkg_name}")
    subprocess.run(["git", "submodule", "update"], cwd=f"{data_dir}/{pkg_name}")
    subprocess.run(config["build"]["command"], cwd=f"{data_dir}/{pkg_name}", shell=True)

def update_packages() -> None:
    for pkg in os.listdir(config_dir):
        if not pkg.endswith(".json"):
            continue
        update_package(pkg[:-5])

def main() -> None:
    if not os.path.isdir(data_dir):
        os.mkdir(data_dir)
    if not os.path.isdir(config_dir):
        os.mkdir(config_dir)

    parser = argparse.ArgumentParser(description="manage packages built from upstream sources")
    subparsers = parser.add_subparsers(dest="command")
    install = subparsers.add_parser("install", help="install a package")
    install.add_argument("name", help="package name")
    install.add_argument("repo", help="package repository URL")
    install.add_argument("--build", default="make -j$(nproc)", help="build command")
    install.add_argument("--branch", default=None, help="target branch")
    remove = subparsers.add_parser("remove", help="remove a package")
    remove.add_argument("name", nargs="*", help="package names")
    update = subparsers.add_parser("update", help="update all packages")
    update.add_argument("name", nargs="*", help="package names")
    subparsers.add_parser("reset", help="delete all packages and data")
    args = parser.parse_args()

    if args.command == "install":
        install_package(args.name, {
            "source": {
                "type": "git",
                "remote": args.repo,
                "branch": args.branch
            },
            "build": {
                "type": "command",
                "command": args.build,
            }
        })
    elif args.command == "remove":
        for name in args.name:
            remove_package(name)
    elif args.command == "update":
        if len(args.name) == 0:
            update_packages()
        else:
            for name in args.name:
                update_package(name)
    elif args.command == "reset":
        shutil.rmtree(data_dir)
        shutil.rmtree(config_dir)
    else:
        parser.print_help()
        parser.exit(1)

if __name__ == "__main__":
    main()
