#!/usr/bin/env python3
# Copyright (C) 2026 RZ781
#
# This file is part of bman.
#
# bman is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bman is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.

import os, shutil, subprocess, json, argparse
from typing import Any, Optional

json_dict = dict[str, Any]

class SourceConfig:
    def to_json(self) -> json_dict: raise NotImplementedError
    def get_clean_source(self, pkg_name: str) -> None: raise NotImplementedError
    def update_source(self, pkg_name: str) -> None: raise NotImplementedError
    @staticmethod
    def from_json(json: json_dict) -> "SourceConfig":
        if "type" not in json:
            raise Exception("source configuration does not contain type")
        if json["type"] == "git":
            if "remote" not in json:
                raise Exception("git configuration does not contain remote")
            elif not isinstance(json["remote"], str):
                raise Exception("git remote is not a string")
            elif "branch" not in json:
                raise Exception("git configuration does not contain branch")
            elif not isinstance(json["branch"], str):
                raise Exception("git branch is not a string")
            return GitSourceConfig(json["remote"], json["branch"])
        else:
            raise Exception(f"source configuration has unknown type {json["type"]}")

class GitSourceConfig(SourceConfig):
    def __init__(self, remote: str, branch: str):
        self.remote = remote
        self.branch = branch
    def to_json(self) -> json_dict:
        return {"type": "git", "remote": self.remote, "branch": self.branch}
    def get_clean_source(self, pkg_name: str) -> None:
        clone_command = ["git", "clone", self.remote, pkg_name, "--depth", "1"]
        if self.branch is not None:
            clone_command += ["--branch", self.branch]
        subprocess.run(clone_command, cwd=data_dir)
        subprocess.run(["git", "submodule", "update", "--init"], cwd=f"{data_dir}/{pkg_name}")
    def update_source(self, pkg_name: str) -> None:
        subprocess.run(["git", "pull"], cwd=f"{data_dir}/{pkg_name}")
        subprocess.run(["git", "submodule", "update"], cwd=f"{data_dir}/{pkg_name}")

class BuildConfig:
    def to_json(self) -> json_dict: raise NotImplementedError
    def build(self, pkg_name: str) -> None: raise NotImplementedError
    @staticmethod
    def from_json(json: json_dict) -> "BuildConfig":
        if "type" not in json:
            raise Exception("build configuration does not contain type")
        if json["type"] == "make":
            return MakeBuildConfig()
        elif json["type"] == "command":
            if "command" not in json:
                raise Exception("command build configuration does not contain command")
            elif not isinstance(json["command"], str):
                raise Exception("command is not a string")
            return CommandBuildConfig(json["command"])
        else:
            raise Exception(f"build configuration has unknown type {json["type"]}")

class MakeBuildConfig(BuildConfig):
    def to_json(self) -> json_dict:
        return {"type": "make"}
    def build(self, pkg_name: str) -> None:
        subprocess.run(["make", f"-j{os.cpu_count()}"], cwd=f"{data_dir}/{pkg_name}")

class CommandBuildConfig(BuildConfig):
    def __init__(self, command: str):
        self.command = command
    def to_json(self) -> json_dict:
        return {"type": "command", "command": self.command}
    def build(self, pkg_name: str) -> None:
        subprocess.run(self.command, cwd=f"{data_dir}/{pkg_name}", shell=True)

class Package:
    def __init__(self, name: str, source: SourceConfig, build: BuildConfig):
        self.name = name
        self.source = source
        self.build = build
    def to_json(self) -> json_dict:
        return {"source": self.source.to_json(), "build": self.build.to_json()}
    def install(self) -> None:
        self.source.get_clean_source(self.name)
        self.build.build(self.name)
        with open(f"{config_dir}/{self.name}.json", "w") as f:
            json.dump(self.to_json(), f)
    def remove(self) -> None:
        assert_package_exists(self.name)
        shutil.rmtree(f"{data_dir}/{self.name}")
        os.remove(f"{config_dir}/{self.name}.json")
    def update(self) -> None:
        assert_package_exists(self.name)
        self.source.update_source(self.name)
        self.build.build(self.name)
    @staticmethod
    def from_json(pkg_name: str, json: json_dict) -> "Package":
        if "source" not in json:
            raise Exception("configuration does not contain source")
        if "build" not in json:
            raise Exception("configuration does not contain build")
        return Package(pkg_name, SourceConfig.from_json(json["source"]), BuildConfig.from_json(json["build"]))
    @staticmethod
    def from_name(pkg_name: str) -> "Package":
        assert_package_exists(pkg_name)
        with open(f"{config_dir}/{pkg_name}.json") as f:
            config = json.load(f)
        return Package.from_json(pkg_name, config)

data_dir = os.environ.get("BMAN_DATA_DIR", os.path.expanduser(f"~/.local/share/bman"))
config_dir = os.environ.get("BMAN_CONFIG_DIR", os.path.expanduser(f"~/.config/bman"))

def assert_package_exists(pkg_name: str) -> None:
    if not os.path.isfile(f"{config_dir}/{pkg_name}.json"):
        raise Exception(f"package {pkg_name} does not exist")
    elif not os.path.isdir(f"{data_dir}/{pkg_name}"):
        raise Exception(f"package {pkg_name} has no data directory")

def list_packages() -> list[str]:
    return [pkg[:-5] for pkg in os.listdir(config_dir) if pkg.endswith(".json")]

def update_packages() -> None:
    for pkg in list_packages():
        Package.from_name(pkg).update()

def main() -> None:
    if not os.path.isdir(data_dir):
        os.mkdir(data_dir)
    if not os.path.isdir(config_dir):
        os.mkdir(config_dir)

    parser = argparse.ArgumentParser(description="manage packages built from upstream sources")
    subparsers = parser.add_subparsers(dest="command")

    install = subparsers.add_parser("install", help="install a package")
    install.add_argument("name", help="package name")
    install.add_argument("repo", help="package repository URL")
    install.add_argument("--build", help="build command")
    install.add_argument("--branch", default=None, help="target branch")

    install_config = subparsers.add_parser("install-config", help="install a package from a config file")
    install_config.add_argument("name", help="package name")
    install_config.add_argument("config", help="name of config file")

    remove = subparsers.add_parser("remove", help="remove a package")
    remove.add_argument("name", nargs="*", help="package names")

    update = subparsers.add_parser("update", help="update all packages")
    update.add_argument("name", nargs="*", help="package names")

    subparsers.add_parser("reset", help="delete all packages and data")

    subparsers.add_parser("list", help="list all packages")

    get_config = subparsers.add_parser("get-config", help="print the json config for a package")
    get_config.add_argument("name", help="package name")

    args = parser.parse_args()

    if args.command == "install":
        package = Package(
            args.name,
            GitSourceConfig(args.repo, args.branch),
            MakeBuildConfig() if args.build is None else CommandBuildConfig(command=args.build)
        )
        package.install()
    elif args.command == "install-config":
        with open(args.config) as f:
            config = json.load(f)
        package = Package.from_json(args.name, config)
        package.install()
    elif args.command == "remove":
        for name in args.name:
            package = Package.from_name(name)
            package.remove()
    elif args.command == "update":
        if len(args.name) == 0:
            update_packages()
        else:
            for name in args.name:
                package = Package.from_name(name)
                package.update()
    elif args.command == "reset":
        shutil.rmtree(data_dir)
        shutil.rmtree(config_dir)
    elif args.command == "get-config":
        package = Package.from_name(args.name)
        print(json.dumps(package.to_json(), indent=4))
    elif args.command == "list":
        for pkg in list_packages():
            print(pkg)
    else:
        parser.print_help()
        parser.exit(1)

if __name__ == "__main__":
    main()
