#!/usr/bin/env python3
# Copyright (C) 2026 RZ781
#
# This file is part of bman.
#
# bman is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# bman is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.

import sys, os, shutil, subprocess, json, typing

class GitSourceConfig(typing.TypedDict):
    type: typing.Literal["git"]
    remote: str

class CommandBuildConfig(typing.TypedDict):
    type: typing.Literal["command"]
    command: str

class PackageConfig(typing.TypedDict):
    source: GitSourceConfig
    build: CommandBuildConfig

NAME = "bman"

data_dir = os.path.expanduser(f"~/.local/share/{NAME}")
config_dir = os.path.expanduser(f"~/.config/{NAME}")

if not os.path.isdir(data_dir):
    os.mkdir(data_dir)
if not os.path.isdir(config_dir):
    os.mkdir(config_dir)

def assert_n_args(minimum: int, maximum: int | None = None) -> None:
    if maximum is None:
        maximum = minimum
    if len(sys.argv) < minimum:
        exit(f"{NAME}: expected at least {minimum} arguments, got {len(sys.argv)}")
    if len(sys.argv) > maximum:
        exit(f"{NAME}: expected at most {maximum} arguments, got {len(sys.argv)}")

def install_package(pkg_name: str, config: PackageConfig) -> None:
    subprocess.run(["git", "clone", config["source"]["remote"], pkg_name, "--depth", "1"], cwd=data_dir)
    subprocess.run(config["build"]["command"], cwd=f"{data_dir}/{pkg_name}", shell=True)
    with open(f"{config_dir}/{pkg_name}.json", "w") as f:
        json.dump(config, f)

def remove_package(pkg_name: str) -> None:
    shutil.rmtree(f"{data_dir}/{pkg_name}")
    os.remove(f"{config_dir}/{pkg_name}.json")

def update_packages() -> None:
    for pkg in os.listdir(config_dir):
        if not pkg.endswith(".json"):
            continue
        with open(f"{config_dir}/{pkg}") as f:
            config: PackageConfig = json.load(f)
        pkg = pkg[:-5]
        os.chdir(f"{data_dir}/{pkg}")
        subprocess.run(["git", "pull"], cwd=f"{data_dir}/{pkg}")
        subprocess.run(config["build"]["command"], cwd=f"{data_dir}/{pkg}", shell=True)

if len(sys.argv) < 2:
    exit(f"{NAME}: no command provided")

if sys.argv[1] == "install":
    assert_n_args(4, 5)
    install_package(sys.argv[2], {
        "source": {
            "type": "git",
            "remote": sys.argv[3],
        },
        "build": {
            "type": "command",
            "command": sys.argv[4] if len(sys.argv) == 5 else "make -j${nproc}",
        }
    })
elif sys.argv[1] == "remove":
    assert_n_args(3)
    remove_package(sys.argv[2])
elif sys.argv[1] == "update":
    assert_n_args(2)
    update_packages()
elif sys.argv[1] == "reset":
    assert_n_args(2)
    shutil.rmtree(data_dir)
    shutil.rmtree(config_dir)
else:
    exit(f"{NAME}: unknown command {sys.argv[1]}")
